# Generated by Django 3.2.8 on 2021-10-14 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Preferowana data i godzina rejsu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.CharField(choices=[('1h', '1 godzina'), ('2h', '2 godziny'), ('3h', '3 godziny')], max_length=2, verbose_name='Długość rejsu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Informacje dodatkowe'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numbers',
            field=models.CharField(choices=[('<6', 'mniej niż 6 osób'), ('6-10', 'od 6 do 10 osób'), ('>10', 'ponad 10 osób')], max_length=5, verbose_name='Zakładana liczba osób'),
        ),
    ]
