# Generated by Django 3.2.8 on 2021-10-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0003_auto_20211015_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
    ]
