# Generated by Django 3.2.8 on 2021-10-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0004_remove_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Imię i nazwisko'),
        ),
    ]
