# Generated by Django 3.2.8 on 2021-10-18 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nadwislanin', '0006_auto_20211015_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='Potwierdzenie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email_text',
            field=models.TextField(blank=True, verbose_name='Wiadomość e-mail'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Nowe zapytanie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Nazwa użytkownika'),
        ),
    ]
