# Generated by Django 3.2.8 on 2021-10-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0007_auto_20211018_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email_text',
            field=models.TextField(default='Dziękujemy za zainteresowanie rezerwacją rejsu Nadwiślaninem. Potwierdzamy możliwość jego zorganizowania w dniu ... o godzinie ... . Pozdrawiamy serdecznie, załoga Nadwiślanina', verbose_name='Wiadomość e-mail'),
        ),
    ]
