# Generated by Django 3.2.8 on 2021-11-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0008_alter_reservation_email_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='numbers',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.CharField(choices=[('1', 'Mochty-smok tajemnice i legendy'), ('2', 'Kierunek Leoncin na styku trzech kultur'), ('3', 'Spichlerz - Modlin widziany z Narwi')], max_length=2, verbose_name='Długość rejsu'),
        ),
    ]
