# Generated by Django 3.2.8 on 2021-11-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0009_auto_20211106_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
        migrations.AddField(
            model_name='reservation',
            name='tour',
            field=models.CharField(choices=[('1', 'Mochty-smok tajemnice i legendy'), ('2', 'Kierunek Leoncin na styku trzech kultur'), ('3', 'Spichlerz - Modlin widziany z Narwi')], default=1, max_length=2, verbose_name='Wybrana wycieczka'),
            preserve_default=False,
        ),
    ]
