# Generated by Django 3.2.8 on 2021-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0010_auto_20211106_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email_text',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email_text_one',
            field=models.TextField(default='Dziękujemy za zainteresowanie rezerwacją rejsu Nadwiślaninem. Potwierdzamy możliwość jego zorganizowania w dniu ... o godzinie ... . Prosimy o dokonanie wpłaty na podany numer konta: 63 8011 0008 0040 0409 6821 0001. Jesteśmy do dyspozycji w przypadku dodatkowych pytań. Pozdrawiamy serdecznie, załoga Nadwiślanina', verbose_name='Wiadomość e-mail I'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email_text_two',
            field=models.TextField(default='Dziękujemy za dokonanie wpłaty za rejs Nadwiślaninem. Potwierdzamy rezerwację w terminie ... . Prosimy o przybycie 15 minut przed potwierdzoną godziną rejsu. W systemie rezerwacyjnym po zalogowaniu istnieje możliwość sprawdzenia jego szczegółów. Do zobaczenia w "Modlin Plaża". Pozdrawiamy, załoga Nadwiślanina', verbose_name='Wiadomość e-mail II'),
        ),
    ]
