# Generated by Django 3.2.8 on 2021-11-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadwislanin', '0011_auto_20211112_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email_text_one',
            field=models.TextField(default='Dziękujemy za zainteresowanie rezerwacją rejsu Nadwiślaninem. \nPotwierdzamy możliwość jego zorganizowania w dniu ... o godzinie ... . \nProsimy o dokonanie wpłaty na podany numer konta: 63 8011 0008 0040 0409 6821 0001. \nJesteśmy do dyspozycji w przypadku dodatkowych pytań. \nPozdrawiamy serdecznie, \nzałoga Nadwiślanina', verbose_name='Wiadomość e-mail I'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email_text_two',
            field=models.TextField(default='Dziękujemy za dokonanie wpłaty za rejs Nadwiślaninem. \nPotwierdzamy rezerwację w terminie ... . \nProsimy o przybycie 15 minut przed potwierdzoną godziną rejsu. \nW systemie rezerwacyjnym po zalogowaniu istnieje możliwość sprawdzenia jego szczegółów. \nDo zobaczenia w „Modlin Plaża”! \nPozdrawiamy, \nzałoga Nadwiślanina', verbose_name='Wiadomość e-mail II'),
        ),
    ]
